In [13]:
# ejercicio 1

import numpy as np

# crear matrices de dimension dim1xdim2 (ambas funciones deben tener las mismas dimensiones para ser sumadas)
dim1 = int(input("ingrese la cantidad de filas de las matrices"))
dim2 = int(input("ingrese la cantidad de columnas de las matrices"))

# generar la matriz1
matriz1 = np.random.random((dim1,dim2))
print(matriz1)

# generar la matriz2
matriz2 = np.random.random((dim1,dim2))
print(matriz2)

# imprimir la suma de las matrices 
print(matriz1+matriz2)

ingrese la cantidad de filas de las matrices3
ingrese la cantidad de columnas de las matrices3
[[0.57479731 0.8295562  0.34617029]
 [0.38518884 0.53237587 0.26867619]
 [0.13143516 0.02059745 0.24370477]]
[[0.46758106 0.9604836  0.03928012]
 [0.26037005 0.20979049 0.22356869]
 [0.20603825 0.03289394 0.6792262 ]]
[[1.04237837 1.7900398  0.38545041]
 [0.64555889 0.74216636 0.49224488]
 [0.33747341 0.05349139 0.92293097]]


In [15]:
# ejercicio 2
id_4 = np.identity(4)
id_4

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [149]:
# lista de cero y uno
lista = [0, 1]

# crear una matriz de 3x3 con valores 0 y 1 
matriz3 = np.random.choice(lista, size=(3,3))
print(matriz3)

# transformar valores 0 en false
matrizbool1 = np.where(matriz3 == 0, "False", matriz3)
matrizbool1

[[1 0 1]
 [0 1 0]
 [0 1 0]]


array([['1', 'False', '1'],
       ['False', '1', 'False'],
       ['False', '1', 'False']], dtype='<U21')

In [72]:
# ejericio 4

array2 = np.arange(0,100,2)
matriz4 = np.reshape(array2,(25,2))
matriz4



array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18],
       [20, 22],
       [24, 26],
       [28, 30],
       [32, 34],
       [36, 38],
       [40, 42],
       [44, 46],
       [48, 50],
       [52, 54],
       [56, 58],
       [60, 62],
       [64, 66],
       [68, 70],
       [72, 74],
       [76, 78],
       [80, 82],
       [84, 86],
       [88, 90],
       [92, 94],
       [96, 98]])